
CREATE DATABASE IF NOT EXISTS my_crud_angular;
USE my_crud_angular;

CREATE TABLE IF NOT EXISTS USUARIOS (
    idUsuario INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    telefono VARCHAR(15),
    email VARCHAR(100)
);

ALTER TABLE USUARIOS
ADD COLUMN puesto VARCHAR(50) NOT NULL AFTER email,
ADD COLUMN estado ENUM('ONLINE', 'OFFLINE') DEFAULT 'OFFLINE' AFTER puesto,
ADD COLUMN fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER estado,
ADD COLUMN fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER fecha_registro;
